import { IExperience } from '../component/experience/IExperience';

const experience: IExperience.Payload = {
  disable: false,
  list: [
    {
      title: '원스토어(주)',
      position: '개발팀장 대행 / Tech Lead',
      startedAt: '2024-04',
      descriptions: [
        '원웹샵(webshop.onestore.net) 개발/오픈 리딩 - API 서버 개발 및 인프라 구성',
        '국내/글로벌 웹서비스 Project Leading - m.onestore.co.kr, m.onestore.net, m.enjoystore.com.tw',
        '레거시 리팩토링 및 재개발 주도, 글로벌 웹서비스 k8s 이전 주도',
        '스티커 스토어(SMS 이모티콘 판매 시스템) 재개발 - 구독 기능 추가하여 오픈',
      ],
      skillKeywords: [
        'Kotlin',
        'Spring Boot',
        'Spring Data JPA',
        'Spring Security',
        'Java',
        'Spring',
        'Redis',
        'Oracle',
        'React',
        'Next.js',
        'Azure',
        'AKS',
        'Docker',
        'Argo CD',
        'Jenkins',
        'Swagger',
      ],
    },
    {
      title: '(주)이마트',
      position: '개발 리딩 / Tech Leader',
      startedAt: '2022-06',
      endedAt: '2024-04',
      descriptions: [
        '고객 분석 시스템(대시보드) 개발 - backend tech 리더, 프로젝트 인원 6명',
        'BigQuery → PostgreSQL 데이터 파이프라인 개발, 160만 건 일 단위 Sync',
        'EKS 구성 및 GitHub Actions 기반 CI/CD 구축',
        '이마트 영수증 데이터 조회 API 개발 및 EKS 서비스 환경 구축',
      ],
      skillKeywords: [
        'Kotlin',
        'Spring Boot',
        'Spring Data JPA',
        'Spring Batch',
        'Spring Security',
        'AWS',
        'EKS',
        'Helm',
        'Airflow',
        'K8s CronJob',
        'GitHub Actions',
        'PostgreSQL',
        'BigQuery',
        'DynamoDB',
      ],
    },
    {
      title: '원스토어(주)',
      position: '개발 리딩',
      startedAt: '2016-03',
      endedAt: '2022-06',
      descriptions: [
        '원스토어 결제시스템 Core(원페이) 백엔드 개발/운영 - 담당자 1인',
        '원스토어 인앱결제 SDK Open API 설계/개발',
        '레거시 배치 시스템을 Spring Batch로 업그레이드, 약 200여 개 Jenkins Job 현행화 및 서버 이전',
        '원스토리 서비스 API bug fix / 성능 개선 - 해당 연도 SR 평가 수상',
        '회원 모듈 운영/개발 - Project Leader, 수행 인원 3명',
        '원스토리 서버 분리 - 유지보수 용이성 증대',
      ],
      skillKeywords: [
        'Java',
        'Spring',
        'Spring Boot',
        'Spring Batch',
        'iBATIS',
        'Oracle',
        'RabbitMQ',
        'Azure',
        'Jenkins',
      ],
    },
    {
      title: '에스케이플래닛(주)',
      position: 'Software Engineer',
      startedAt: '2013-06',
      endedAt: '2016-03',
      descriptions: [
        'IN-APP 결제시스템 개발/운영 - 8,000라인 이상의 JSP 레거시 코드 분석 후 모듈화',
        '매월 1일 서버 폭주로 인한 장애를 아파치 캐시, mod_ratelimit, 로드 밸런싱, KeepAlive 설정으로 최소화',
        'NFC Open Platform - 모바일 신용카드/교통카드 발급 Open API 서버 구축 및 상용화',
        '리팩토링 및 불필요 모듈 제거로 nGrinder 측정 결과 기존 대비 2.7배 처리 능력 향상',
      ],
      skillKeywords: ['Java', 'Spring', 'JSP', 'Apache', 'Oracle', 'nGrinder', 'JavaScript'],
    },
    {
      title: 'SK 씨앤씨(주)',
      position: 'Software Engineer (계약직)',
      startedAt: '2011-07',
      endedAt: '2013-06',
      descriptions: [
        'UCMS(유심 관리 시스템) 운영 및 Spring Framework 재개발',
        '레거시 Java 소스를 Spring Framework로 재개발 - 개발 리더 2인 중 1인, 총 인원 10여 명',
      ],
      skillKeywords: ['Java', 'Spring', 'Oracle', 'JavaScript', 'jQuery'],
    },
    {
      title: '인크로스(주) 관악지점',
      position: 'Software Engineer',
      startedAt: '2010-12',
      endedAt: '2011-07',
      descriptions: [
        'SKT 무선 NATE 서비스 개발 - 생활 In 화보서비스 및 문자 중계 서비스 개발/운영',
        '2010 월드컵 실시간 문자 중계 서비스 - 오픈 1주일 전 개발 시작하여 서비스 오픈 성공',
        'SK Telecom Tbag(TCloud) 운영 PM',
      ],
      skillKeywords: ['Java', 'WAP', 'JavaScript', 'Tomcat'],
    },
    {
      title: '이노에이스(주)',
      position: 'Software Engineer',
      startedAt: '2009-01',
      endedAt: '2010-12',
      descriptions: [
        'SK Telecom ZoneCasting Server - 근거리 통신망(ZigBee)을 이용한 방송 서비스',
        'TCP/UDP를 동시 지원하는 멀티 프로세스·멀티 스레드 데몬 개발, 단독 진행',
        'P2P 및 방송 패킷 동시 전송 구현, 방송 기준치를 상회하는 전송 성능 달성',
      ],
      skillKeywords: ['Unix-C', 'TCP/UDP', 'Multi Process', 'Multi Thread'],
    },
    {
      title: '(주)젬백스링크',
      position: 'Software Engineer',
      startedAt: '2006-11',
      endedAt: '2009-01',
      descriptions: [
        'SKT 모바일 네트워크 게임 게이트웨이 개발 - TCP/IP 멀티 프로세스, 멀티 스레드 데몬',
        '게임아이템 판매 게이트웨이 설계/개발 및 오픈, SKT 본사에서 게임 개발자 설명회 진행',
        'LG U+ 1000자 문자서비스 버그를 파견 2주 만에 해결하여 조기 진급 포상',
      ],
      skillKeywords: ['Unix-C', 'Java', 'EJB', 'Multi Process', 'Multi Thread'],
    },
  ],
};

export default experience;
